# Add 'size: small' to any changes below 10 lines
'PR/Size: Small':
  max: 9
  
# Priority is large because it would be
# easy to playtest this
'Priority: Large':
  max: 9

# Add 'size: medium' to any changes between 10 and 100 lines
'PR/Size: Medium':
  min: 10
  max: 99

# Priority starts to dwindle as the PR
# increases in scope
'Priority: Medium':
  min: 10
  max: 99

# Add 'size: large' to any changes of at least 100 lines
'PR/Size: Large':
  min: 100

# "Too big! Ill review it after the update or smth"
'Priority: Small':
  min: 100
