# Add 'size: small' to any changes below 10 lines
'PR/Size: Small':
  max: 9
'Priority: High':
  max: 9

# Add 'size: medium' to any changes between 10 and 100 lines
'PR/Size: Medium':
  min: 10
  max: 99
'Priority: Medium':
  max: 9

# Add 'size: large' to any changes of at least 100 lines
'PR/Size: Large':
  min: 100
'Priority: Small':
  max: 9
