# Add Documentation tag to PR's changing markdown files, or anything in the docs folder
'PR: documentation':
- changed-files:
  - any-glob-to-any-file:
      - docs/*
      - '**/*.md'

# Add Haxe tag to PR's changing haxe code files
'PR: haxe':
- changed-files:
  - any-glob-to-any-file: '**/*.hx'

# Add GitHub tag to PR's changing yml files, or anything in the .github folder 
'PR: github':
- changed-files:
  - any-glob-to-any-file:
      - github/*
      - '**/*.yml'

# labeler "full" schema

# enable labeler on issues, prs, or both.
enable:
  issues: true
  prs: true
# comments object allows you to specify a different message for issues and prs

comments:
  issues: |
    Thanks for opening this issue!
    I have applied any labels matching special text in your title and description.

    Please review the labels and make any necessary changes.
  prs: |
    Thanks for the contribution!
    I have applied any labels matching special text in your title and description.

    Please review the labels and make any necessary changes.

# Labels is an object where:
# - keys are labels
# - values are objects of { include: [ pattern ], exclude: [ pattern ] }
#    - pattern must be a valid regex, and is applied globally to
#      title + description of issues and/or prs (see enabled config above)
#    - 'include' patterns will associate a label if any of these patterns match
#    - 'exclude' patterns will ignore this label if any of these patterns match
labels:
  'Priority: Medium':
    include:
      - 'BUG'
      - 'ISSUE'
      - 'Bug'
      - 'Issue'
    exclude: []
  'Priority: Large':
    include:
      - '[CRASH]'
      - 'Crash'
    exclude: []
  'Status: Addiction':
    include:
      - 'FEATURE'
      - 'Feature'
      - 'PR'
      - 'Pull request'
      - 'ADDITION'
      - 'Addiction'
      - 'PULL REQUEST'
    exclude: []
