# Add Documentation tag to PR's changing markdown files, or anything in the docs folder
'PR/Type: Documentation':
- changed-files:
  - any-glob-to-any-file:
      - docs/*
      - '**/*.md'

# Add Haxe tag to PR's changing haxe code files
'PR/Type: Haxe':
- changed-files:
  - any-glob-to-any-file: '**/*.hx'
  
'PR/Type/Haxe: Stage modification':
- changed-files:
  - any-glob-to-any-file: '**/stages/*.hx'  

'PR/Type/Haxe: Global':
- changed-files:
  - any-glob-to-any-file: 'source/Global.hx'
  
'PR/Type/Haxe: Save data':
- changed-files:
  - any-glob-to-any-file: '**/savedata/*.hx'
  
# Add GitHub tag to PR's changing yml files, or anything in the .github folder 
'PR/Type: Github':
- changed-files:
  - any-glob-to-any-file:
      - github/*
      - '**/*.yml'
      
