# Add Documentation tag to PR's changing markdown files, or anything in the docs folder
'PR/Type: Documentation':
- changed-files:
  - any-glob-to-any-file:
      - docs/*
      - '**/*.md'

# Add Haxe tag to PR's changing haxe code files
'PR/Type: Haxe':
- changed-files:
  - any-glob-to-any-file: '**/*.hx'

# Add GitHub tag to PR's changing yml files, or anything in the .github folder 
'PR/Type: Github':
- changed-files:
  - any-glob-to-any-file:
      - github/*
      - '**/*.yml'

# A file changed = an addition
'Status: Addition':
- changed-files:
  - any-glob-to-any-file:
      - '*'
