name: Close Stale Issues

on:
  schedule:
    - cron: '0 12 1-31 * *'

jobs:
  closeStaleIssues:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v9.1.0
        with:
                # The message to post on the issue when tagging it. If none provided, will not mark issues stale.
                stale-issue-message: 'This issue is stale and thus has been given the "Response: Stale" tag'
                # The message to post on the pull request when tagging it. If none provided, will not mark pull requests stale.
                stale-pr-message: 'This PR is stale and thus has been given the "Response: Stale" tag'
                # The message to post on the issue when closing it. If none provided, will not comment when closing an issue.
                close-issue-message: 'This issue is stale for too long and thus has been closed automatically'
                # The message to post on the pull request when closing it. If none provided, will not comment when closing a pull requests.
                close-pr-message: 'This PR is stale for too long and thus has been closed automatically'
                # The number of days old an issue can be before marking it stale. Set to -1 to never mark issues as stale automatically. Override "days-before-stale" option regarding only the issues.
                days-before-issue-stale: 15
                # The number of days old a pull request can be before marking it stale. Set to -1 to never mark pull requests as stale automatically. Override "days-before-stale" option regarding only the pull requests.
                days-before-pr-stale: 30
                # The number of days to wait to close an issue after it being marked stale. Set to -1 to never close stale issues. Override "days-before-close" option regarding only the issues.
                days-before-issue-close: 30
                # The number of days to wait to close a pull request after it being marked stale. Set to -1 to never close stale pull requests. Override "days-before-close" option regarding only the pull requests.
                days-before-pr-close: 60
                # The label to apply when an issue is stale.
                stale-issue-label: 'Response: Stale'
                # The reason to use when closing an issue.
                close-issue-reason: 'Stale'
                # The label to apply when a pull request is stale.
                stale-pr-label: 'Response: Stale'
                # Only issues or pull requests with all of these labels are checked if stale. Defaults to `` (disabled) and can be a comma-separated list of labels.
                only-labels: 'Response: Unknown,Response: Ignored'
