name: 'Close stale issues and PRs'
on:
  schedule:
    - cron: '* * * * *'
    
permissions:
  contents: write # only for delete-branch option
  issues: write
  pull-requests: write

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v9
        with:          
          stale-issue-message: 'This issue is stale and has automatically been closed'
          stale-pr-message: 'This PR is stale and has automatically been closed'

          exempt-pr-labels: 'Response: Unknown'
          exempt-issue-labels: 'Response: Unknown'
          
          stale-issue-label: 'Response: Stale'
          stale-pr-label: 'Response: Stale'
          
          only-labels: 'Response: Unreproducible bug,Respose: Planned,Response: Fixed,Response: Ignored,Response: Intentional,Response: Developer created'

          days-before-stale: 1

          days-before-close: 0